[package]
name = "aptos_discover"
version = "1.0.0"
authors = []

[addresses]
dapp='0x66cd3cc5d2d724d9eacc30a35cf61aef36c0fe69bc1c7ecb9444cae9a39aecd2'
admin='0x296e53ce1956ebdef5d969f3189a00b0ca29f2d377b311e30872202d4072b19b'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"


[dev-dependencies]
